### PR TITLE
Mention `jupyter-lite.json` in the pyodide docs

### PR DESCRIPTION
**Pull request by jtpio**
## References

Follow-up to the discussion in https://github.com/jupyterlite/pyodide-kernel/issues/44.

## Code changes

Clearly mention `jupyter-lite.json` in the documentation for specifying a custom Pyodide URL to avoid confusion.

## User-facing changes

Docs update.

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by lesteve** [comment]
Great, thanks!

I am a bit confused though, what is the difference between `jupyter-lite.json` and `jupyter_lite_config.json` mentioned in https://jupyterlite.readthedocs.io/en/latest/reference/cli.html?

**Comment by jtpio** [comment]
> difference between `jupyter-lite.json` and `jupyter_lite_config.json`

Typically `jupyter-lite.json` is for runtime configuration (page load). While `jupyter_lite_config.json` is for build time configuration (when running `jupyter lite build`).

I realize this may indeed not be clear so there should be a more visible note somewhere in the docs to improve that.

**Comment by jtpio** [comment]
There is also some the difference between `overrides.json` and `jupyter-lite.json` as reported in https://github.com/jupyterlite/jupyterlite/issues/784.

I'll open a follow-up PR to address these questions.

**Comment by lesteve** [comment]
OK thanks a lot for the details!

**Comment by jtpio** [comment]
> I'll open a follow-up PR to address these questions.

Opened https://github.com/jupyterlite/jupyterlite/pull/1062

**Pull request merged**
