### PR TITLE
Add download button as example settings

### PR DESCRIPTION
**Pull request by pierrepo**
## References

This PR addresses issue #1049 based on a suggestion by @jtpio 

## Code changes

No code change. Only appropriate settings in `overrides.json`

## User-facing changes

User will have a download button in the notebook menu bar:

notebook-menu-bar-download-button

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by pierrepo** [comment]
@jtpio not sure about the location of the image in the documentation (`_static` folder ?).

**Comment by jtpio** [comment]
Thanks @pierrepo for this!


> not sure about the location of the image in the documentation (`_static` folder ?).

Maybe we could just use the GitHub link for now:

```
![notebook-menu-bar-download-button](https://user-images.githubusercontent.com/733861/231521636-35d5a1c8-c80d-4d76-800e-426948cbc011.png)
```

Other places in the docs also use direct links like this one (to avoid checking in large animated gifs). At some point we can consider keeping the images in the repo.

**Comment by pierrepo** [comment]
@jtpio 
> Maybe we could just use the GitHub link for now:

Sure. Does it mean the image is hosted by GitHub but not on the repo? How long will this link be available?

Do I need to remove the image from the repo?

**Comment by jtpio** [comment]
> Sure. Does it mean the image is hosted by GitHub but not on the repo? How long will this link be available?

Yes. I don't think the links ever expire actually.

> Do I need to remove the image from the repo?

Yes let's remove it for now.

**Comment by pierrepo** [comment]
@jtpio it should be ok now.

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
