### PR TITLE
Update to JupyterLab 4.3 and Notebook 7.3

### PR DESCRIPTION
**Pull request by jtpio**
## References

Looking into https://github.com/jupyterlite/jupyterlite/issues/1482 to check if there is something major that may be breaking.

## Code changes

- [x] Bump `@jupyterlab`, `@jupyter-notebook` packages
- [x] Bump `jupyterlab` and `notebook` dependencies
- [x] Bump `jupyterlab` and `notebook` in conda environments
- [x] Add to the migration guide for 0.5.0
- [x] Fix UI tests

## User-facing changes

- JupyterLab changelog: https://jupyterlab.readthedocs.io/en/latest/getting_started/changelog.html
- Notebook changelog: https://jupyter-notebook.readthedocs.io/en/latest/changelog.html

## Backwards-incompatible changes

TBD

### CODE REVIEW

**Comment by jtpio** [comment]
cc @martinRenou @bollwyvl for awareness

I would like to merge this one soon and follow-up with more fixes if needed, so we can have a first `0.5.0` pre-release based on JupyterLab 4.3 and Notebook 7.3 available.

**Comment by jtpio** [comment]
Arf, there seems to be some issues with menu when trying the build from RTD: https://jupyterlite--1514.org.readthedocs.build/en/1514/_static/lab/index.html

image

Not sure yet what the cause of this is.

**Comment by bollwyvl** [comment]
Bummer, I will look this weekend. It's hard to reason about
runtime-injected things that can change without any warning, even for
already-built sites. Sigh.

**Comment by jtpio** [comment]
There is probably something going on with the changes in this PR, as the RTD preview for the recently created https://github.com/jupyterlite/jupyterlite/pull/1536 seems to be fine (on 4.2 / 7.2 packages):

image

**Comment by bollwyvl** [comment]
It looks like we lost `core.css`: in chromiums this leaves the `body{margin: 8px;}` default which _seems_ to match up with the offset we're seeing. Not sure about the `z-index`...

**Comment by jtpio** [comment]
Thanks @bollwyvl for the hint!

Indeed, this was likely related to https://github.com/jupyterlab/jupyterlab/pull/16519.

https://github.com/jupyterlite/jupyterlite/pull/1514/commits/2c04cc7ab8fad75004a10fbd9419701c0789f639 seems to be fixing on RTD now:

image

**Comment by jtpio** [comment]
OK, moving forward with this then to make the first 0.5.0 alpha.

Happy to follow-up with more fixes if needed. Thanks!

**Pull request merged**
