### PR TITLE
Update to pyodide 0.19.0

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- acting on changes from #429

## Code changes

- [x] update default CDN location
- [x] update version for cached pyodide testing
- [x] remove `nbformat` shim
- [x] update `micropip` imports 
  - [x] `micropip.micropip` to `micropip._micropip` :blush:  
  - [x] `_get_url` to `fetch_string` 

## User-facing changes

- ???

## Backwards-incompatible changes

- ???

### CODE REVIEW

**Comment by bollwyvl** [comment]
Ok, 7959e7d might actually build :crossed_fingers:

**Comment by bollwyvl** [comment]
Run ran through all of the pyodide examples on RTD (sometimes with 3-4 open at a time) and it didn't crash my browsers (chrome, FF) or throw any untoward errors.

My semi-janky FS notebook did have a `borrowed proxy was automatically destroyed` console error, but this is user error :blush: . I was glad to see the `cwd` is now `/home/pyodide`, as this will make things a bit more natural going forward.

`micropip.install("...", keep_going=True)` is _great_, and have turned it on for our startup stuff, but have _not_ put it into the examples, as i feel we want them to look as simple as possible. Perhaps in the `ipython 8` era we'll be able to harmonize the `%pip` experience.

Was able to drop our last super-hard pin on jsonschema (:tada:), and am fairly confident we could drop _all_ of our pins, at this point, but don't have to do it on this PR.

Otherwise, I noted some issues (race conditions?) when trying to rebuild with a locally-cached pyodide a bunch of time, but these are entirely self-created issues... i need to rethink how we do our "winner take all" `_output/jupyter-lite.json`, and do it with patches or something... or maybe just fix some `file_dep` entries.

**Comment by jtpio** [comment]
Thanks, this looks exciting!

**Comment by jtpio** [comment]
Wondering whether we might be able to drop the following patch too?

https://github.com/jupyterlite/jupyterlite/blob/ff2780102db530d12ae948f78ca0fbebe2cfcf22/packages/pyolite-kernel/py/pyolite/pyolite/mocks.py#L6-L11

Based on this: https://blog.pyodide.org/posts/function-pointer-cast-handling/

**Comment by bollwyvl** [comment]
At least `altair` and `plotly` no longer hits the recursion limit... i don't recall anywhere else that ran into it. As jedi was mentioned, perhaps this will help us there too.

This also means we can probably add back in the lighter-weight patch mechanism form #239, and get matplotlib/numpy off the critical path to first interactive computing.

**Comment by bollwyvl** [comment]
> we can probably add back in the lighter-weight patch mechanism form #239

At least as a first attempt: no. This should probably be a separate PR anyway:

```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 494, in eval_code_async
    await CodeRunner(
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 347, in run_async
    await coroutine
  File "<exec>", line 3, in <module>
  File "/lib/python3.9/site-packages/pyolite/__init__.py", line 20, in <module>
    from .display import LiteStream
  File "/lib/python3.9/site-packages/importhook/loader.py", line 85, in exec_module
    mod = self.loader.exec_module(module, *args, **kwargs)
  File "/lib/python3.9/site-packages/pyolite/display.py", line 4, in <module>
    from IPython.core.displayhook import DisplayHook
  File "/lib/python3.9/site-packages/importhook/loader.py", line 85, in exec_module
    mod = self.loader.exec_module(module, *args, **kwargs)
  File "/lib/python3.9/site-packages/IPython/__init__.py", line 56, in <module>
    from .terminal.embed import embed
  File "/lib/python3.9/site-packages/importhook/loader.py", line 85, in exec_module
    mod = self.loader.exec_module(module, *args, **kwargs)
  File "/lib/python3.9/site-packages/IPython/terminal/embed.py", line 14, in <module>
    from IPython.core.magic import Magics, magics_class, line_magic
  File "/lib/python3.9/site-packages/importhook/loader.py", line 85, in exec_module
    mod = self.loader.exec_module(module, *args, **kwargs)
  File "/lib/python3.9/site-packages/IPython/core/magic.py", line 20, in <module>
    from . import oinspect
  File "/lib/python3.9/site-packages/importhook/loader.py", line 85, in exec_module
    mod = self.loader.exec_module(module, *args, **kwargs)
  File "/lib/python3.9/site-packages/IPython/core/oinspect.py", line 46, in <module>
    from pygments.lexers import PythonLexer
ImportError: cannot import name 'PythonLexer' from 'pygments.lexers' (/lib/python3.9/site-packages/pygments/lexers/__init__.py)

```

As pyodide does its own loader stuff, we'll almost certainly need something not-quite-off-the-shelf....

**Comment by jtpio** [comment]
Looks like `0.19.0` is out :tada: https://github.com/pyodide/pyodide/releases/tag/0.19.0

**Comment by bollwyvl** [comment]
Saw the update and [blog post](https://blog.pyodide.org/posts/0.19-release/).

Doing a clean install and test here, should have an update shortly. I feel like we'd want to do a refresh of the (retro)lab stable releases to get some of those updates, but it would be cool to get a new lite release out soon.

**Comment by jtpio** [comment]
Sounds good, I'll open a PR to update to the latest lab and retro packages.

**Comment by dsblank** [comment]
> This also means we can probably add back in the lighter-weight patch mechanism form #239, and get matplotlib/numpy off the critical path to first interactive computing.

That will be great! Nice work!

**Comment by bollwyvl** [comment]
@dsblank does https://github.com/jupyterlite/jupyterlite/pull/433#issuecomment-1001262582 ring any bells? If you had time to look at it again, it would be a solid follow-up, but let's not block on it...

**Comment by bollwyvl** [comment]
Ran through the notebooks on RTD, and didn't run into any hiccups.

**Comment by bollwyvl** [comment]
Speaking of hiccups, seems like GHA is Having A Day generally... not going to bother re-running stuff right now.

**Comment by jtpio** [comment]
Nice, thanks @bollwyvl :+1: 

CI now seems to be passing after restarting it.

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by dsblank** [comment]
> @dsblank does #433 (comment) ring any bells? If you had time to look at it again, it would be a solid follow-up, but let's not block on it... 

Agreed! I hope to have some "open source time" this weekend.

**Pull request merged**
