### PR TITLE
Add RELEASE.md

### PR DESCRIPTION
**Pull request by jtpio**
## References

Dumping some information about cutting new releases for reference.

This is still a manual process for now, but should improve with #121.

## Code changes

Dev docs.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by bollwyvl** [comment]
I highly prefer releasing CI-built assets (even if CI isn't doing the actual permissioned upload), as it's almost impossible to screw up with a dirty env, and then the SHASUMS have a clear provenance to a particular build.

I also generally use `npm publish` (rather than `yarn` or `lerna`), and have even gone so far as to template out a release script .

**Comment by jtpio** [comment]
Yes if we adopt the jupyter releaser then it will be releasing CI assets.

For now we create the GitHub release after pushing the tag to the repo with the workflow (will add that to RELEASE.md), so the steps are a bit out of order.

**Comment by jtpio** [comment]
But we could already update the process to first push the release commit to generate the new assets on CI, and then download locally and publish them (for now it's just the PyPI package).

**Comment by jtpio** [comment]
Should be good enough for now, to be improved and iterated on soon.

**Pull request merged**
