### PR TITLE
Update to jupyterlab 3.1.0rc2

### LINKED ISSUE #282: Upgrade to JupyterLab 3.1.0rc2
### Problem

https://pypi.org/project/jupyterlab/3.1.0rc2/

### Proposed Solution

- do the upgrade, a la #207

### Additional context

- should restore context menus #265
- blocked by conda-forge PR
  - (should be up within in an hour or two, using wrong computer)

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- fixes #282
- [RTD](https://jupyterlite--283.org.readthedocs.build/en/283/_static/lab/index.html) 
- [binder](https://mybinder.org/v2/gh/bollwyvl/jupyterlite/gh-282-jupyterlab-310rc2?urlpath=lab)

## Code changes

- [x] bump baseline verisons
- [x] resolve yarn, environment
- [x] check package versions vs imports in `check`
- [x] handle the context plugin
  - > didn't have to do anything :tada:
- [x] reorganize non-kernel/shell patches/mocks while investigating demo fails
  - > each patch/mock is now wrapped in a `try`, and no longer brings down the whole runtime if one fails
- [x] retro stuff??

## User-facing changes

| thing | screenshot |
|-|-|
| see context menu |  Screenshot from 2021-07-21 16-08-38

## Backwards-incompatible changes

- ???

### CODE REVIEW

**Comment by bollwyvl** [comment]
Looks like the `altair` example is failing on restart-and-run-all....

**Comment by bollwyvl** [comment]
Plotly also failing:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-0f083345bb1a> in <module>
      4 fig.add_trace(go.Bar(y=[1, 4, 3, 2]))
      5 fig.update_layout(title = 'Hello Figure')
----> 6 fig.show()

/lib/python3.8/site-packages/plotly/basedatatypes.py in show(self, *args, **kwargs)
   3396         import plotly.io as pio
   3397 
-> 3398         return pio.show(self, *args, **kwargs)
   3399 
   3400     def to_json(self, *args, **kwargs):

/lib/python3.8/site-packages/_plotly_utils/importers.py in __getattr__(import_name)
     34             rel_module = ".".join(rel_path_parts[:-1])
     35             class_name = import_name
---> 36             class_module = importlib.import_module(rel_module, parent_name)
     37             return getattr(class_module, class_name)
     38 

/lib/python3.8/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

/lib/python3.8/importlib/_bootstrap.py in _gcd_import(name, package, level)

/lib/python3.8/importlib/_bootstrap.py in _find_and_load(name, import_)

/lib/python3.8/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/lib/python3.8/importlib/_bootstrap.py in _load_unlocked(spec)

/lib/python3.8/importlib/_bootstrap_external.py in exec_module(self, module)

/lib/python3.8/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/lib/python3.8/site-packages/plotly/io/_renderers.py in <module>
     10 from plotly import optional_imports
     11 
---> 12 from plotly.io._base_renderers import (
     13     MimetypeRenderer,
     14     ExternalRenderer,

/lib/python3.8/site-packages/plotly/io/_base_renderers.py in <module>
     10 from plotly import utils, optional_imports
     11 from plotly.io import to_json, to_image, write_image, write_html
---> 12 from plotly.io._orca import ensure_server
     13 from plotly.io._utils import plotly_cdn_url
     14 from plotly.offline.offline import _get_jconfig, get_plotlyjs

/lib/python3.8/site-packages/plotly/io/_orca.py in <module>
     13 from pathlib import Path
     14 
---> 15 import tenacity
     16 from six import string_types
     17 

/lib/python3.8/site-packages/tenacity/__init__.py in <module>
    513 
    514 if tornado:
--> 515     from tenacity.tornadoweb import TornadoRetrying

/lib/python3.8/site-packages/tenacity/tornadoweb.py in <module>
     21 from tenacity import RetryCallState
     22 
---> 23 from tornado import gen
     24 
     25 if typing.TYPE_CHECKING:

ImportError: cannot import name 'gen' from 'tornado' (unknown location)
```

**Comment by bollwyvl** [comment]
`fast` looks hard broken, both the document renderer and the mime renderer

```
Uncaught TypeError: t.on is not a function
    resetSeqs 681.80b3439aec1db6dfd35f.js:2
    e 681.80b3439aec1db6dfd35f.js:2
    resetSeqs 681.80b3439aec1db6dfd35f.js:2
    i 681.80b3439aec1db6dfd35f.js:2
    _loadSeqs 681.80b3439aec1db6dfd35f.js:2
    initialize 681.80b3439aec1db6dfd35f.js:2
    a 681.80b3439aec1db6dfd35f.js:2
    i 681.80b3439aec1db6dfd35f.js:2
    i 681.80b3439aec1db6dfd35f.js:2
```

**Comment by bollwyvl** [comment]
While some demos are broken, I don't think it's worth blocking the merge on those, in this case... they probably just each need separate issues.

**Comment by bollwyvl** [comment]
mmm... the plotly fix... doesn't.  still looking into it...

**Comment by bollwyvl** [comment]
Plotly fix appears to work locally... looking into altair...

**Comment by bollwyvl** [comment]
The altair fail is from overloading `builtins.input` with a `JsProxy`... investigating...

**Comment by bollwyvl** [comment]
Looks like both `plotly` and `altair` are back to working... no further changes planned, as `fasta`'s been on the ropes for a while...

Screenshot from 2021-07-21 19-10-54

**Comment by jtpio** [comment]
Thanks!!

The fasta standalone file has been an issue for a while and could be tracked separately yet. However the renderer in the notebook should work (https://github.com/jupyterlite/jupyterlite/issues/284 and https://github.com/jupyterlab/jupyterlab/issues/10675 for reference, not a blocker for this PR).

**Comment by jtpio** [comment]
>  retro stuff??

We need to add the new `@jupyterlab/application-extension:context-menu` plugin to the build:

https://github.com/jupyterlite/jupyterlite/blob/9680e3ec215f25ce82f199cc61e33c5bb4669fd3/app/retro/index.template.js#L51

I'll push a commit for this.

**Comment by jtpio** [comment]
> We need to add the new @jupyterlab/application-extension:context-menu plugin to the build:

Hmm looks like https://github.com/jupyterlite/jupyterlite/pull/283/commits/28d31bc96e528762b6c52d8250f7f2a58df83eb9 is not enough. Looking into doing the update in Retro first: https://github.com/jupyterlab/retrolab/pull/186

**Comment by jtpio** [comment]
> Looks like both `plotly` and `altair` are back to working

Were those failures related to new versions of the libraries?

**Comment by bollwyvl** [comment]
> Looks like both plotly and altair are back to working
>
> Were those failures related to new versions of the libraries?
>

Nah, more transient deps. I assume people just hadn't been reviewing every
notebook every pr.

Due to mocking tornado, we have to mock... More tornado. Because plotly
might want to call home. Or something. Uses tenacity.

Altair was broken by overloading builtins.input with a pyodide.JsProxy.
this offended toolz.

**Comment by bollwyvl** [comment]
The various above transient dep issues are part of why #45 is so important... four years later, all the jyve demos still work (to the extent that they every worked :rofl:).

A full archival-grade workflow will eventually need to figure out how to capture _everything it possibly can_ and put it together in the deployable folder/archive... this will require kernel-specific knowledge, of course, but i think we're getting there. Getting to `pyodide` + `whateverdide` as built (and deduplicated) by `conda-forge` will be needed for the "real" fix, but i think we can get there with `pyolite` and multi-indexing, patched `micropip` in the near term.

investing in the JS kernels, we can likely figure out a prefetching strategy for es modules... i trust "hot" js packages probably the _least_ in the whole stack.

**Comment by jtpio** [comment]
> Hmm looks like [28d31bc](https://github.com/jupyterlite/jupyterlite/commit/28d31bc96e528762b6c52d8250f7f2a58df83eb9) is not enough

https://github.com/jupyterlite/jupyterlite/pull/283/commits/137a88a94248e2394741112bfa32c941d9e604e1 should fix it for retro.

**Comment by jtpio** [comment]
> The various above transient dep issues are part of why #45 is so important... four years later, all the jyve demos still work (to the extent that they every worked rofl).

Fully agree :+1: Also just for the simple case of having everything easily working offline or in flight mode.

**Comment by bollwyvl** [comment]
I didna look at any of the RTC stuff... what are we expecting to have actually been fixed?

**Comment by bollwyvl** [comment]
Actually, RTC (and FASTA :exploding_head: ) lookin fine:
Screenshot from 2021-07-22 11-51-29

**Comment by bollwyvl** [comment]
Hoisted some observed errors to #286... not worth blocking here.

**Comment by jtpio** [comment]
> and FASTA :exploding_head: 

That is weird, as this seems to be reproducible upstream (https://github.com/jupyterlab/jupyterlab/issues/10675)

**Comment by bollwyvl** [comment]
> seems to be reproducible

best kind of :bug:

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
As mentioned above, let's track the outstanding issue in separate issues (some are already opened).

**Pull request merged**
