### PR TITLE
Try the latest dev Pyodide

### PR DESCRIPTION
**Pull request by jtpio**
## References

The latest dev version might include some `micropip` fixes as noticed and discussed in https://github.com/giswqs/leafmap/issues/55.

We can use the RTD preview for testing: https://jupyterlite--178.org.readthedocs.build/en/178/

## User-facing changes

Using the latest (dev) version of Pyodide.

## Backwards-incompatible changes

Probably some, so keeping as a draft for now.

### CODE REVIEW

**Comment by bollwyvl** [comment]
Got some interest in the INDEXDB/FS stuff, as well... and I see that `bokeh` (and therefore `pyyaml` (and therefore `libyaml`)) also got in recently, all of it running on 3.9. Fun stuff coming up!

**Comment by bollwyvl** [comment]
I think we're circling the drain on getting access to more filesystems on https://github.com/pyodide/pyodide/pull/1596. The API won't be super-well documented, but here's at least [a test](https://github.com/pyodide/pyodide/blob/b3f9d837873e79f49fcae0d28aa3db8f36243859/src/tests/test_filesystem.py) that shows some how some stuff might be used.

**Comment by jtpio** [comment]
Really nice to see this landing upstream soon!

If anyone would like to pick up this PR and start updating to the latest Pyodide, feel free to do so. Thanks!

**Comment by bollwyvl** [comment]
Yeah, so everything's in upstream, but the jsdelivr `dev` assets haven't quite rolled over yet.

Once it is, we should be able to interactively build stuff like:

```py
from pyodide_js import FS
FS.mount()
# put some stuff into the filesystem FROM indexedDB
FS.syncfs(true, ...)
# do some stuff
# put some stuff out of the filesystem TO indexedDB
FS.syncfs(false, ...)
```

The challenge here is that `syncfs` does _all_ the filesystems, so we if were to add some mounts, they would _also_ get updated

Still kinda planning how to apply the new `FS` features most effectively... for example, getting an indexedDB wheel cache going might make it easier to iteratively work on the right stuff on the python side (since kernels would predictably start _much_ faster).

**Comment by bollwyvl** [comment]
Some things that _kinda_ work with what's currently on `dev`:

https://gist.github.com/bollwyvl/616802a1765dc702ee97a0f065adad8c

**Comment by jtpio** [comment]
Closing in favor of #274.

**Pull request closed without merging**
