### PR TITLE
update to jupyterlab 3.4.5

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- n/a

## Code changes

- [x] update to newest `@jupyterlab` packages
- [x] resolve `yarn.lock`
- [x] resolve `examples` wheels, etc.

## User-facing changes

- JSON settings editor should work again 

## Backwards-incompatible changes

- n/a

### CODE REVIEW

**Comment by bollwyvl** [comment]
JSON Settings editor is back:
Screenshot from 2022-08-10 15-32-48

**Comment by bollwyvl** [comment]
haven't done a full pass through RTD notebooks, but this appears ready for review.

**Comment by bollwyvl** [comment]
Aside from the attachments on cytoscape, all the notebooks looks fine on RTD.

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
