### PR TITLE
Update to JupyterLab 3.4.2, add `documentsearch-extension`

### LINKED ISSUE #630: Remove `preferredPath` from `jupyter-lite.json`
https://github.com/jupyterlite/jupyterlite/pull/626 added `preferredPath` to `jupyter-lite.json`:

https://github.com/jupyterlite/jupyterlite/blob/5ced05bfc5e0758a8fdbb3342a4941102562d8d2/app/jupyter-lite.json#L15

This should be removed when https://github.com/jupyterlab/jupyterlab/pull/12521 is available in a JupyterLab release (3.4.1+), when updating JupyterLite to the newer packages.

### PR DESCRIPTION
**Pull request by jtpio**
## References

Update to the latest JupyterLab release.

Fixes #630 

## Code changes

- [x] Update to the `@jupyterlab` 3.4.1 packages
- [x] Drop `preferredPath` from the page config
- [x] Bump to `jupyterlab>=3.4.1`

## User-facing changes

- Small bug fixes.
- Add `@jupyterlab/documentsearch-extension`

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
UI tests passing, also looking good on RTD:

image

image

**Comment by bollwyvl** [comment]
Are we also missing the app-wide search/replace plugin now?

**Comment by jtpio** [comment]
> Are we also missing the app-wide search/replace plugin now?

Ah, looks like it's been missing for a while it seems, looking at the history: https://github.com/jupyterlite/jupyterlite/commits/main/app/lab/package.json

**Comment by jtpio** [comment]
> Ah, looks like it's been missing for a while it seems, looking at the history: https://github.com/jupyterlite/jupyterlite/commits/main/app/lab/package.json

Added in https://github.com/jupyterlite/jupyterlite/pull/640/commits/95da9a299183c1bbbe3ffe86832ac71dee0dd2a1

**Comment by bollwyvl** [comment]
> missing for a while it seems

as mentioned before: it seems like this is something we could at least be validating, if not automating... the lists for `lab`, `retro`, etc. exist someplace in JSON-at-rest in the as-installed packages, and maintaining lists of what we _don't_ want is probably more effective than waiting for refactored features to disappear...

**Comment by jtpio** [comment]
> and maintaining lists of what we _don't_ want is probably more effective than waiting for refactored features to disappear...

Yeah agree. I would like to have something more declarative for sure as discussed elsewhere. Probably just passing these lists as `disabledExtensions` would do the trick. The initial idea was to do it bottom-up and make it opt-in and avoid pick up things we don't want from upstream when updating to new versions. Probably both approaches have pros and cons.

Also related to https://github.com/jupyter/notebook/issues/6399 for notebook.

**Comment by jtpio** [comment]
[This failure](https://github.com/jupyterlite/jupyterlite/runs/6406703731?check_suite_focus=true) looks new, and does not look related to the change.

```
pip._vendor.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.
```

**Comment by bollwyvl** [comment]
> pip._vendor.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.

yeah, have been seeing this elsewhere today... it looks like it might be related to `pip@22.1` and `flit`'s dynamic discovery of the version/description... perhaps if we accept duplicating it in `pyproject.toml` it will work today... not sure what the real solution will be.

**Comment by bollwyvl** [comment]
aw shucks, that bumpversion stuff is rather complex... perhaps if it was inverted so that the `__version__` string was the canonical version, and the tuple was derived, it might work...

**Comment by jtpio** [comment]
Maybe it's a good time to drop `bump2version` and use `tbump` only then, as a follow-up to https://github.com/jupyterlite/jupyterlite/pull/426#issuecomment-983732886.

**Comment by jtpio** [comment]
> **EDIT**: will look into that in a separate PR / issue: #643

This has now been fixed.

**Comment by jtpio** [comment]
CI is now back to green :heavy_check_mark:

**Pull request merged**
