### PR TITLE
Add ipycytoscape to the example federated extensions

### PR DESCRIPTION
**Pull request by jtpio**
## References

Follow-up to #238 

## Code changes

Examples change.

## User-facing changes

Should enable the `ipycytoscape` example notebook back:

image

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by bollwyvl** [comment]
yerp, sry: was stuck with the web ui, and couldn't resolve

**Comment by bollwyvl** [comment]
Could avoid in the future by ensuring `git diff` comes up clean in CI.

**Comment by jtpio** [comment]
No problem!

Looking good on the preview:

image

**Review by bollwyvl — APPROVED** [review]

**Comment by marimeireles** [comment]
Sorry Jeremy, I hadn't understood we also didn't need the deps there.
Thanks for this :))

**Comment by jtpio** [comment]
No worries, it was more of a follow-up to #238 that slightly changed how the federated extensions are installed on the demo site.

**Pull request merged**
