### PR TITLE
Upgrade to JupyterLab 3.1.9, RetroLab 0.3.1

### LINKED ISSUE #299: Update to latest JupyterLab 3.1.7
### Problem

We are still using 3.1.0rcX.

### Proposed Solution

Update all the upstream versions, presumably also for RetroLab... but it does not yet have a release using the latest core upstream packages.

### Additional context

- n/a

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- fixes #299

## Code changes

- [x] bump all the versions
  - [x] `@jupyterlab`
  - [x] `@retrolab`
    - [x] blocked by upstream release: https://github.com/jupyterlab/retrolab/releases/tag/0.3.0 and https://github.com/jupyterlab/retrolab/releases/tag/0.3.1
- [x] resolve the environment/extensions (just kernelspy changed) 

## User-facing changes

- ???

## Backwards-incompatible changes

- ???

### CODE REVIEW

**Comment by bollwyvl** [comment]
Everything looks good on RTD.

**Comment by jtpio** [comment]
RetroLab 0.3.1 is out, just pushed a change for the update:

- https://github.com/jupyterlab/retrolab/releases/tag/0.3.0
- https://github.com/jupyterlab/retrolab/releases/tag/0.3.1

Gonna check on RTD when available, and this should be good to go.

**Comment by jtpio** [comment]
Looks good on the preview, including RTC between lab and retro:


https://user-images.githubusercontent.com/591645/131217821-5f184c7f-2f01-48ba-a3c7-b504a174ae91.mp4

**Comment by datakurre** [comment]
@jtpio Does this mean that JupyterLite now support collaboration by default? How does that work? I have never before used RTC with JupyterLab and I am clueless on how to activate it :flushed:

**Comment by jtpio** [comment]
@datakurre yes it should be enable for the demo site. Some docs about it in: https://jupyterlite.readthedocs.io/en/latest/rtc/index.html

In short appending `?room=test-room&username=myusername` to the URL should enable it.

JupyterLite uses a different provider than stock JupyterLab so the experience might be a bit different (WebRTC in lite and WebSocket in lab). There are still a couple of bugs to fix in JupyterLite but it should be somehow functional already.

**Comment by jtpio** [comment]
> Does this mean that JupyterLite now support collaboration by default?

It's not by default, but we enable it for the demo site here:

https://github.com/jupyterlite/jupyterlite/blob/a12f71c81a5c4bbb31e55bd61dcac358bbe63ba6/examples/jupyter-lite.json#L5

For reference this custom deployment on GitHub Pages also enables it: https://github.com/jtpio/lit/blob/d65ee8adfbd400a70d4422f075937a25ac1ef86c/jupyter-lite.json#L5

**Comment by datakurre** [comment]
@jtpio Thanks. My bad for not checking lite documentation for the instructions.

I am still getting `WebRTC: ICE failed, add a TURN server and see about:webrtc for more details` error on Firefox console, but that's possibly some more generic issue with my Firefox :thinking:

**Pull request merged**
