### PR TITLE
Bump to JupyterLab 3.6.0

### PR DESCRIPTION
**Pull request by fcollonval**
This reverts commit 06c55f0a7320f84c2cffeaf637e69658ef8ef8a8.

## References

Superseeds https://github.com/jupyterlite/jupyterlite/pull/876

## Code changes

Upgrade to 3.6.0 alpha 5

## User-facing changes

Use latest version

### CODE REVIEW

**Comment by martinRenou** [comment]
This probably goes in conflict with https://github.com/jupyterlite/jupyterlite/pull/899 (also in conflict with `main` apparently)

**Comment by fcollonval** [comment]
I fully agree with @jtpio 

With the nice drive approach targeting 4 and as our resources are sparse, I advice to skip touching https://github.com/jupyterlite/jupyterlab-webrtc-docprovider before 4. Hence this implies not upgrading JupyterLite to 3.6.

**Comment by bollwyvl** [comment]
This works for me! I guess it will then be relevant to continue getting upstream bugfixen to a `3.5.x` branch, as well for a while, then... we can't be the only downstream that will be unable to quickly shift and throw a bunch of resources at the new `ydoc`-related upgrades when `4.x` and `notebook 7.x` are coming Real Soon Now :tm:

**Comment by jtpio** [comment]
Closing in favor of https://github.com/jupyterlite/jupyterlite/pull/1019 as we'll skip the update to JupyterLab 3.6.

**Pull request closed without merging**
