### PR TITLE
Expose the Router to be able to add new routes from third-party plugins

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes https://github.com/jupyterlite/jupyterlite/issues/390

Closing in on some potential `0.1.0` API breaking changes so we can soon start releasing `0.1.0` final (#383).

## Code changes

Expose the main `Router` instance so server extensions can add new routes.

## User-facing changes

None

## Backwards-incompatible changes

- [x] Remove the `JupyterServer` and `LiteServiceManager` classes
- [x] Routes are added by the server plugins directly
- [x] Remove `@jupyterlite/server-extension:server` plugin

### CODE REVIEW

**Comment by bollwyvl** [comment]
This is a good first step: breaking up the `_addRoutes` into separate plugins (perhaps co-located with their managers) that use the API would a) make it much clearer how one might use these APIs effectively and b) make it far easier to reason about what is/isn't loaded in case someone wants to overload it.

**Comment by jtpio** [comment]
More code cleaning and route splitting in https://github.com/jupyterlite/jupyterlite/pull/506/commits/e518e4b4322ea0a5ccf03a676ecddb46066f40cf.

This should be better now, and allow for third-party server extensions to easily add new routes, or replace core plugins just like for JupyterLab (via `disabledExtensions` or providing custom ones).

**Comment by bollwyvl** [comment]
This already reads much better than the monolithic `_addRoutes`. 

The architecture this PR currently presents is a bit different from the upstream `jupyter_server`, in that there, one can replace just, e.g. `ContentsManager`, and implement its API, but _not_ have to redefine the routes, which are really the contract with the frontend. Further, the routes are kinda untyped (basically `Request<string>`) which might make it harder still to practically consider replacing them.

So anyhow: the other way (just for consideration) is a pattern where all of the routes stay in the files where they have been moved, but are separated into `thingRoutesPlugin`: e.g. the `contentsPlugin` provides `IContents`, to be consumed by `contentsRoutesPlugin`, which actually adds the routes.

**Comment by jtpio** [comment]
Good point. Especially since the frontends (at least both lab and retro) expect these routes to be functional.

It makes sense to be able to just swap the implementation of the different services, while still keeping the default routes. I'll push a change to split that into the routes plugins.

**Comment by jtpio** [comment]
> It makes sense to be able to just swap the implementation of the different services, while still keeping the default routes. I'll push a change to split that into the routes plugins.

Done in https://github.com/jupyterlite/jupyterlite/pull/506/commits/b2918d34d3f494bf0916d195f69f10a81eb9c5e4

**Comment by jtpio** [comment]
A follow-up would be to add a sample plugin the serverlite cookiecutter to show how to add new routes: https://github.com/jupyterlite/serverlite-cookiecutter-ts

And mention that in the docs: https://jupyterlite.readthedocs.io/en/latest/extensions.html (could be part of https://github.com/jupyterlite/jupyterlite/issues/393)

**Comment by bollwyvl** [comment]
>  just swap the implementation of the different services

Yeah, this feels good: now the routes are written in terms of interfaces, not concrete implementations e.g. `IContents` vs `Contents`.

The only thing that still smells kinda off for a "final" API (i mean, heck, it's still `0.1.0`) is that the HTTP responses are just typed with `string | null`... but we probably don't need to solve everything at this point... perhaps in some future state where we're generating typings from the OpenAPI spec would help.

> sample plugin the serverlite cookiecutter

yeah, very good. i think overloading any of the services isn't ready for someone to do without a thorough reading of the code ... though, anywhere where we can make the default services more composable than the upstream winner-takes-all, is good.  However, completely replacing e.g. contents would be a good long-form tutorial, e.g. integrating with an existing API, using multiple domains to improve security, etc.

**Review by bollwyvl — APPROVED** [review]
might as well move forward: we won't know until we really start trying to implement some non-trivial stuff downstream

**Comment by jtpio** [comment]
Alright let's get this in.

**Pull request merged**
