### PR TITLE
Update to Pyodide `0.20.1a1`

### PR DESCRIPTION
**Pull request by jtpio**
## References

Update to the latest Pyodide.

Currently in alpha: https://github.com/pyodide/pyodide/releases/tag/0.20.1a1

## Code changes

Pyodide update. Will wait until final before moving forward.

## User-facing changes

Pyodide changelog: https://pyodide.org/en/latest/project/changelog.html#unreleased

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by bollwyvl** [comment]
Thanks for starting this. There are some micropip changes we might want to
look into: I think it does better case/hyphen normalization now. I'll take
a look when I have a chance.

**Comment by bollwyvl** [comment]
https://github.com/pyodide/pyodide/issues/2408#issuecomment-1114905175

we of course don't _have_ to use _exactly_ the same normalization scheme as upstream, but it would be very good to do so....

**Comment by bollwyvl** [comment]
also this PR: https://github.com/pyodide/pyodide/pull/2445

**Comment by jtpio** [comment]
Nice thanks @bollwyvl for the links!

Feel free to push directly to the PR, or open a new one if you want to (I'm not touching it for now).

**Comment by psychemedia** [comment]
It looks like v0.21.0a1 may also hit at some point soon... https://github.com/pyodide/pyodide/issues/2740

**Comment by jtpio** [comment]
Arf not sure I follow the versioning there? It seems to be `0.21.0a2`, not `0.20.1a2`: https://github.com/pyodide/pyodide/releases/tag/0.21.0a2

**Comment by bollwyvl** [comment]
new alpha is out:

https://github.com/pyodide/pyodide/releases/tag/0.21.0a3

**Comment by jtpio** [comment]
Linking to the upstream issue tracking the `0.21` release for reference: https://github.com/pyodide/pyodide/issues/2881

**Comment by jtpio** [comment]
Closing in favor of https://github.com/jupyterlite/jupyterlite/pull/756

**Pull request closed without merging**
