### PR TITLE
Fix mamba environment creation command

### PR DESCRIPTION
**Pull request by davidbrochart**
`mamba env update` doesn't seem to be a valid command.

### CODE REVIEW

**Comment by bollwyvl** [comment]
What kind of errors were you seeing? I pretty much exclusively use `env update`, as otherwise you have to blow away the env, or use `-f`.

**Comment by davidbrochart** [comment]
```bash
mamba --version
# 1.2.0

mamba env update --file .binder/environment.yml
# The following arguments were not expected: .binder/environment.yml --file update
# Run with --help for more information
```

**Comment by bollwyvl** [comment]
sounds like a regression in mamba

**Comment by jtpio** [comment]
Is there an issue tracking this in mamba?

**Comment by davidbrochart** [comment]
Yes: https://github.com/mamba-org/mamba/issues/2369

**Comment by davidbrochart** [comment]
It seems to be caused by a conflict when both `mamba` (e.g. through `mambaforge`) and `micromamba` are installed.

**Comment by jtpio** [comment]
Thanks @davidbrochart for opening the issue upstream and the extra context :+1:

**Pull request closed without merging**
