### PR TITLE
Disable jedi to fix tab completion issue

### PR DESCRIPTION
**Pull request by qqdaiyu55**
Related issue: https://github.com/jupyterlite/jupyterlite/issues/259

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

cc @martinRenou who might know if this is related to a change upstream

**Comment by martinRenou** [comment]
As said by @qqdaiyu55 in #259, this could be related: ipython/ipython#12887

I know that people have been complaining in the past that the completion does not behave properly in IPython when jedi is installed. I believe it's not jedi's fault, but the usage of jedi in IPython. Anyway I guess disabling jedi is good 👍🏽

**Comment by martinRenou** [comment]
> I know that people have been complaining in the past that the completion does not behave properly in IPython when jedi is installed

See https://github.com/ipython/ipython/issues/11530

**Comment by martinRenou** [comment]
Thanks @qqdaiyu55!

**Pull request merged**
