### PR TITLE
fix file size handling in drivefs

### PR DESCRIPTION
**Pull request by katotetsuro**
## References

add `size` property to drivefs
details in #1508

- comlink.worker.ts in jupyterlite-pyodide-kernel also needs to refer this build
- truncate logic for scenarios such as opening existing files in write mode is not included

## Code changes

- add `size` property to `IEmscriptenFSNode`
- set size property when creating new file
- ~~handling size property when creating/modifying content (WIP)~~

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by martinRenou** [comment]
Thanks a lot!

> handling size property when creating/modifying content (WIP)

Would you like us to wait for you to look into it?

We can also get this PR in first, and update the size properly in a separate PR.

**Comment by juntyr** [comment]
I'm still slightly suspicious that the size is stored as a separate property, which can get out of sync. Would it be possible to remove it entirely and to always compute the size based on the content?

**Comment by katotetsuro** [comment]
> always compute the size based on the content?

Is it something like setting size to content.length here ? It seems possible to me.
Since it looks like the content is always being read anyway just by calling getattr (sorry if I’m wrong), there doesn’t seem to be any downside in terms of processing time.

https://github.com/jupyterlite/jupyterlite/blob/main/packages/contents/src/drivecontents.ts#L199

**Comment by katotetsuro** [comment]
> https://github.com/jupyterlite/jupyterlite/blob/main/packages/contents/src/drivecontents.ts#L199

since `{ content: false }` is used in the GET request here, it seems that returning the size based on the actual content.length is not immediately feasible.

@martinRenou 

> We can also get this PR in first, and update the size properly in a separate PR.

As you suggested, it would be helpful for me if the size adjustment could be handled in a separate PR. I also took a quick look at the truncate logic, but it didn’t seem straightforward to me now. Thanks!

**Pull request closed without merging**
