### PR TITLE
Self-hosting MathJax 

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- includes/blocked by #310
- continues towards a baseline for #45

### CLI build time
- adds a build-time MathJax addon which will bundle mathjax assets if 
  - provided by `--mathjax-dir` 
  - installed next to `jupyter-server-mathjax` (obeys `--ignore-sys-prefix`)

### our build/docs
- includes `--mathjax-dir`, because we use `--ignore-sys-prefix`

## User-facing changes

- even fewer CDN requests!

## Backwards-incompatible changes

- `jupyter-server-mathjax` only ships the default configuration... if a user has that package installed and configured `mathjaxConfig` some other way, it won't find the assets
  - this is verified in `check`, but only for `lite`-managed assets (not custom CDN)

### CODE REVIEW

**Comment by bollwyvl** [comment]
This looks ok on RTD.

**Comment by jtpio** [comment]
Thanks @bollwyvl!

Mind updating that PR now that #310 has been merged?

**Comment by bollwyvl** [comment]
Hm, I didn't add any docs for this... probably needs (automation of) it...

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
> Hm, I didn't add any docs for this... probably needs (automation of) it...

Would you like to do this as part of this PR? Otherwise we can track that separately.

**Comment by bollwyvl** [comment]
> Would you like to do this as part of this PR? Otherwise we can track that separately.

Working on tests/docs presently...

**Comment by bollwyvl** [comment]
Woof, that went a bit deeper than expected, but so it goes. No further changes planned!

**Comment by bollwyvl** [comment]
I don't know what to do about how long RTD takes...

**Comment by jtpio** [comment]
> I don't know what to do about how long RTD takes...

Do you think it takes longer to build on RTD? The logs show a build time similar to the version on `main`:

image

**Comment by bollwyvl** [comment]
Guess it just seemed longer last time. There are hundreds of files in the
mathjax distribution, of course... guess that's the price for durability!
Everything seems fine now.

**Comment by jtpio** [comment]
Thanks!

**Pull request merged**
