### PR TITLE
Fix file size handling for the contents drive

### LINKED ISSUE #1472: DriveFS cannot overwrite-truncate existing file
DriveFS currently doesn't handle setting the `size` attribute here:

https://github.com/jupyterlite/jupyterlite/blob/82007cea732ac122f3fa2b12f3f694d16af5c575/packages/contents/src/drivefs.ts#L295

This makes `open("file", "w").close()` fail silently, i.e. an existing file is not truncated.

### LINKED ISSUE #1508: File size in the DriveFS is broken
## Description

In jupyterlite-core v0.4.3, file sizes in the DriveFS (e.g. via `os.stat`) are broken. Downgrading to v0.4.2 changes the breakage (less cases are affected) but doesn't fix it. Since #1497 seems to have touched this code, @katotetsuro might be able to find the issue.

## Reproduce

1. Go to https://jupyterlite.readthedocs.io/en/stable/_static/lab/index.html in a browser that supports the service worker so that DriveFS will be used (check the console)
2. Open a new notebook
3. Run the following code:

```python
import os

with open("a.txt", "wb") as f:
    f.write(b"abc" * 1000)

print(os.path.getsize("a.txt"))
# prints 0 (wrong)

with open("a.txt", "rb") as f:
    print(len(f.read()))
# prints 3000 (correct)
```

This issue is also related to #1472: opening the file in write mode again (which should reset the file to zero size) just overrides existing content but never truncates the length.

## Expected behavior

File sizes should be correct and truncating writes should work.

## Context
- JupyterLite version: 0.4.3

### LINKED ISSUE #1529: .csv file size showing as 0B
Using current https://jupyterlite.github.io/demo/lab/index.html I generate lots of images correctly listed in file tab, however the .csv I generate which is not empty (numbers show when opening it in JupyterLite tab, or in Excel after download) is listed with a file size of 0B

### PR DESCRIPTION
**Pull request by juntyr**
## References

Fixes #1472
Fixes #1508 
Fixes #1529

Supersedes #1511

## Code changes

- Implements `setattr size` by getting, truncating or extending, and writing back the content file
- Fixes file save file size handling by being explicit when the stored content is a partial binary string and when it is decoded to its format

## User-facing changes

Bug fixes

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by juntyr** [comment]
Interestingly, at least #1508 doesn't reproduce on the latest main branch deployment but does on my own one, which uses jupyterlite v0.4.4 as well but uses Pyodide v27 (dev). So perhaps this is an issue that will only materialise with the next Pyodide release?

**Comment by juntyr** [comment]
I did some quick testing with the ReadTheDocs version and uploading large PDFs and notebooks seems to still work

**Comment by jtpio** [comment]
Thanks @juntyr for this! I'll try to have a look soon.

cc @martinRenou who may also be interested

**Comment by jtpio** [comment]
@juntyr maybe it could be a good time to start looking into adding UI tests for file uploads?

We have been tracking that in https://github.com/jupyterlite/jupyterlite/issues/1027. Maybe this could have also helped catch such regressions, and help make sure it does not break again later.

**Comment by juntyr** [comment]
If you want the test to be added in this PR, I'll need your help as I've never written a UI test before

**Comment by jtpio** [comment]
> If you want the test to be added in this PR, I'll need your help as I've never written a UI test before

I guess it would be fine to do it separately too, since it may need some time. And also since this PR fixes a few issues it would be great to make it available to users sooner.

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by juntyr** [comment]
> > If you want the test to be added in this PR, I'll need your help as I've never written a UI test before
> 
> I guess it would be fine to do it separately too, since it may need some time. And also since this PR fixes a few issues it would be great to make it available to users sooner.

What’s your current timeline for the next path release? If the fix could be released sometime next week it would be fantastic (I’m trying to publish a release of my project before the holidays)

**Comment by jtpio** [comment]
I think we can make a new release now from `main`, before a `0.5.0` with https://github.com/jupyterlite/jupyterlite/pull/1514.

**Comment by jtpio** [comment]
Released: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.4.5

Thanks @juntyr for your fixes! Feel free to report more issues if you find any during your testing.

**Comment by juntyr** [comment]
> Released: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.4.5
> 
> Thanks @juntyr for your fixes! Feel free to report more issues if you find any during your testing.

Thanks @jtpio for the quick release! I think the pyodide-kernel needs a release as well (with the jupyterlite deps bumped) since its workers bundle the drive contents.

Since I can only test the combination of new jupyterlite + old pyodide-kernel right now, the file size issues appear fixed (this one seems to be in the "inner" layer that the kernel workers call but don't inline), but the file truncation logic doesn't run yet (this one seems to be in the "outer" layer that is inlined in the kernel workers)

**Comment by juntyr** [comment]
I've opened https://github.com/jupyterlite/pyodide-kernel/pull/146

**Pull request merged**
