### PR TITLE
Revert importhook for now

### PR DESCRIPTION
**Pull request by jtpio**
## References

Another attempt at fixing #248 by reverting https://github.com/jupyterlite/jupyterlite/pull/239

Closes #249

### CODE REVIEW

**Comment by jtpio** [comment]
It's possible the extra decorators add a couple more level of depths.

We can try on https://jupyterlite--89.org.readthedocs.build/en/250/_static/lab/index.html when the preview is ready.

**Comment by jtpio** [comment]
Looks good on the preview with Chromium 91:

image

**Comment by jtpio** [comment]
@davidbrochart would you be able to test with the preview? https://jupyterlite--250.org.readthedocs.build/en/250/_static/lab/index.html

**Comment by jtpio** [comment]
cc @dsblank as you might have more insights on `importhook`

**Comment by dsblank** [comment]
No, no real insights.... just watching and testing :)

**Comment by davidbrochart** [comment]
> @davidbrochart would you be able to test with the preview? https://jupyterlite--250.org.readthedocs.build/en/250/_static/lab/index.html

Yes, it works fine.

**Comment by jtpio** [comment]
Merging to fix #248 and get a release out.

@dsblank the work in #239 is great and works great in Firefox. Maybe we can try to get it back in right after and see how we can deal with the recursion limit issue with Chromium?

**Comment by dsblank** [comment]
@jtpio Thanks! Can you say more about what exactly is happening, and why jupyterlite is setting the recursion limit? Is this an issue with history in jupyterlite?

**Comment by jtpio** [comment]
@dsblank there was some investigation done by @lrowe in https://github.com/jupyterlite/jupyterlite/pull/113#issuecomment-851072065 which led to setting an arbitrary value for the recursion limit, so it also works with Altair.

Looks like it's a tricky one to get right. Maybe the next version of Pyodide will make that easier to deal with.

**Comment by dsblank** [comment]
Wow, that is a tricky one, and explains the problem. I'll keep an eye on that so that we can bring back importhooks for lazy patching.

**Pull request merged**
