### PR TITLE
Update to JupyerLab 3.2.6 and RetroLab 0.3.16

### PR DESCRIPTION
**Pull request by jtpio**
## References

Update to the latest `@jupyterlab` and `@retrolab` packages to grab new features and fixes.

## Code changes

- [x] Update to the latest `@jupyterlab` and `@retrolab` packages
- [x] Update Python packages

## User-facing changes

Same as in upstream lab and retro

## Backwards-incompatible changes

Should be none

### CODE REVIEW

**Comment by jtpio** [comment]
CI is green and looks good on the RTD preview.

**Comment by bollwyvl** [comment]
Nice. If you're feeling good about it, go ahead, and I can update my stuff... might not get everyhing back to happy this evening...

**Comment by jtpio** [comment]
Rebased and CI all green.

**Comment by jtpio** [comment]
Will cut a release later today.

**Comment by bollwyvl** [comment]
:sunglasses: Sounds good.

**Comment by jtpio** [comment]
`0.1.0a19` is out: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0a19

**Pull request merged**
