### PR TITLE
Docs: fix path to `overrides.json`

### PR DESCRIPTION
**Pull request by agoose77**
This PR corrects (I believe) the path to the overrides file.

### CODE REVIEW

**Review by bollwyvl — APPROVED** [review]
good catch! :mag:

**Comment by bollwyvl** [comment]
@agoose77 made some more tweaks, let me know if they make sense and this can be merged

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
> @agoose77 made some more tweaks, let me know if they make sense and this can be merged

Merging as it looks good. @agoose77 feel free to open a new PR if we want to make further changes, thanks!

**Comment by agoose77** [comment]
I was flying / travelling the last couple of days and missed this activity. Thanks for the contributions!

**Pull request merged**
