### PR TITLE
Add route for licenses, include licenses in app bundle

### LINKED ISSUE #233: Show bundled JS libraries, versions, and licenses
### Problem

As a JupyterLite site builder or end user, it is pretty hard to know what software are in my final, shipped site.

### Proposed Solution

- enable the [license file webpack plugin](https://github.com/jupyterlab/jupyterlab/blob/v3.1.0b1/jupyterlab/staging/webpack.prod.config.js#L18) 
- add `licensesUrl` to `jupyter-config-data`? (it doesn't load the UI if this is missing)
- add a serverlite route for `/api/licenses`
- implement a license bundle finder
- enable the `@jupyterlab/help-extension:licenses` plugin (if not already done)

### Additional context

Somewhere in the lab 3.1 alpha progression, we got `/api/licenses` into `jupyterlab_server` (and some helper consumer stuff in `jupyterlab`) which reveals the precise name, version, license, and full license text of the core bundle and all federated extensions (there are none in the wild yet) from `(app_dir/static/|labextensions/(*/)?*/)third-party-licenses.json`.

A number of changes occurred along the way, as well as a few regressions, so we might have to wait for #207  `b2` (with the menu fix) but otherwise should be fairly straightforward.

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- fixes #233
- supersedes #234
  - doesn't include some of the testing changes, as there are actually extensions with third-party licenses in the wild to smoke test, now
  - sadly, a _lot_ of `@jupyterlab` upstreams are missing licenses at present

## Code changes

- adds `@jupyterlite/licenses` server route
- adds `@jupyterlite/types`
  - currently only owns `IFederatedExtensions`
  - used by `settings` and `licenses`
- resolves demo examples 
- skip duration checks in pypy tests

## User-facing changes

- Lab
  - adds the _Help -> Licenses_ viewer
  
Screenshot from 2022-02-21 18-52-36

## Backwards-incompatible changes

- moves `IFederatedExtension` out of settings into new `@jupyterlite/types`

## Follow-on

- add licenses to retrolab upstream
  - dialog?
- add licenses to repl
  - ???

### CODE REVIEW

**Comment by bollwyvl** [comment]
Gah, getting some nasty cache issues... changing `config-utils.js` is pretty obnoxious... don't really know how to improve it without increasing complexity...

**Comment by jtpio** [comment]
Thanks @bollwyvl.

Looks like there a couple of conflicts to fix after the route reorganization in https://github.com/jupyterlite/jupyterlite/pull/506.

But otherwise looks good :+1:

**Comment by bollwyvl** [comment]
Ha yeah, I should get this in... Thanks for the reminder...

**Comment by bollwyvl** [comment]
Welp, it's back up to running!

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
