### PR TITLE
Update ESLint dependencies

### PR DESCRIPTION
**Pull request by jtpio**
## References

Attempt at fixing #194 by updating the ESLint dependencies.

Use `--cache` to hopefully mitigate the OoM issues.

## Code changes

Dependency update.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Even if this doesn't fix the memory issue in #194 and tests still pass, we can still do the update anyway.

**Comment by jtpio** [comment]
The allocation failure seems to be reproducible even with this change:

```bash
# edit packages/application-extension/src/index.tsx

git add packages/application-extension/src/index.tsx
git commit
```

**Comment by bollwyvl** [comment]
So can we... cache the cache in CI? Though maybe that's pointless as `lint-js-test` doesn't block anything else....

**Comment by jtpio** [comment]
Checking a little bit locally with `--cache`. Looks like it might have improved a bit, haven't faced that oom yet.

> So can we... cache the cache in CI?

I guess we could?

**Pull request merged**
