### PR TITLE
Update shim packaging and metadata

### LINKED ISSUE #564: Add jupyterlab-myst to dev/demo environment
### Problem

We use "full" JupyterLab to write some of the executable docs, and use some myst markdown opinions. `jupyterlab-myst` would make some of these less awkward that the default renderer (though some like raw `rst` can't be helped). 

It might _also_ be fun in the demo site: as it brings along `jupyterlab-markup` which does mermaidjs, etc.

### Proposed Solution

- [ ] add `jupyterlab-myst` to docs/binder environment
- [ ] add to demo site

### Additional context

- noted on https://github.com/jupyterlite/jupyterlite/pull/563#discussion_r829996252

### LINKED ISSUE #565: support ipywidgets 7.7.0
### Problem

In the demo site, while `piplite.install("ipywidgets")` works, the newest version, `7.7.0` does not.

```
ValueError: Requested 'widgetsnbextension~=3.6.0', but widgetsnbextension==3.5.0 is already installed
```

### Proposed Solution

Either:
- [ ] ship both versions of the shim package
- [ ] just ship the newer one

### Additional context

- noted on https://github.com/jupyterlite/jupyterlite/pull/563#issuecomment-1071909593

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- fixes #565
- fixes #564

## Code changes

- [x] updates to `flit 3.7.1`
- [x] updates versions of shim packages
- [x] uses PEP 621 `project` metadata instead of `tool.flit`
- [x] resolves demo env
  - [x] `ipywidgets 7.7.0`
  - [x] `jupyterlab-myst`
  - [x] `jupyterlab-markup`  
- [x] bump copyright year, etc.
- [x] removes all non-patched pre-imports (e.g. `matplotlib`) 

## User-facing changes

- `piplite.install("ipywidgets")` will resolve to `ipywidgets 7.7.0`

## Backwards-incompatible changes

- some downstream packages might not yet work
- `nbformat` needs to be installed manually, will impact `plotly` users

### CODE REVIEW

**Comment by bollwyvl** [comment]
Seeing:

```
Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm did not respond in time
```

it's probably worth looking into it....

**Comment by bollwyvl** [comment]
The above issue doesn't seem to _break_ anything, as it only occurs once, at kernel start time, apparently inside `restoreWidgetsFromKernel`... which will almost never return anything from our kernels.

Nothing in particular happens with RTC enabled: this isn't too surprising.

**Comment by jtpio** [comment]
Yes this one is probably coming from this change which landed in `7.7`: https://github.com/jupyter-widgets/ipywidgets/pull/3021

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
