### PR TITLE
Update to JupyterLab 4.2.3

### PR DESCRIPTION
**Pull request by jtpio**
## References

Update to https://github.com/jupyterlab/jupyterlab/releases/tag/v4.2.3

## Code changes

- [x] Bump the `@jupyterlab` dependencies
- [x] Bump the `jupyterlab` dependency

## User-facing changes

Maybe some bug fixes from https://github.com/jupyterlab/jupyterlab/releases/tag/v4.2.3

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by bollwyvl** [comment]
```
Encountered problems while solving:
  - nothing provides requested jupyterlab >=4.2.3,<4.3
```

on it: https://github.com/conda-forge/jupyterlab-feedstock/pull/438

**Comment by bollwyvl** [comment]
Rekicking to see if conda-forge CDN is up-to-date...

**Comment by bollwyvl** [comment]
while cranking stuff, we can likely relax the `importlib-metadata` pin in a bit once `twine 5.1.1` makes it through all the pipes...

**Comment by jtpio** [comment]
> while cranking stuff, we can likely relax/remove the `importlib-metadata` pin once `twine 5.1.1` makes it through all the pipes...

Tracked in https://github.com/jupyterlite/jupyterlite/pull/1426

**Pull request merged**
