### PR TITLE
Include some more accurate file stats from ServiceWorker

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- more work on #671

## Code changes

- report/save `size` in more contents places
  - even if `contents` is `False`, but we happen to have the content around
- more best-effort at calculating `IStats`
  - use the Emscripten `node.id` for inode
  - calculate blocks/blocksize
- add some more narrative and (counter) examples in `virtual_drive.ipynb`

## User-facing changes

- more low-level file options should work
  - sqlite still doesn't, and will need more investigation 

## Backwards-incompatible changes

- n/a

### CODE REVIEW

**Review by martinRenou — APPROVED** [review]
LGTM!

We should probably do the same for the jupyterlab-filesystem-access and jupyterlab-github drives if we can.

**Comment by bollwyvl** [comment]
> We should probably do the same for the jupyterlab-filesystem-access and jupyterlab-github drives if we can.

Does that happen on this repo, or the other side?

**Comment by bollwyvl** [comment]
Created this follow-on #840

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
