### PR TITLE
Basic scaffolding for UI tests

### LINKED ISSUE #6: End to end testing
There should be some end to end testing, ideally with galata: https://github.com/jupyterlab/galata

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes #6 

(still a WIP for now)

## Code changes

Add the basic scaffolding for UI tests with [Galata](https://github.com/jupyterlab/galata) in JupyterLite in the top-level `ui-tests` folder so it's self contained.

It follows a similar approach as in `jupyterlab` and `ipywidgets`.

### TODO

- [ ] Pending upstream PR to not generate workspaces: https://github.com/jupyterlab/galata/pull/71
- [ ] Expose `jupyterlab` app in the browser (`--expose-app-in-browser`)
- [ ] Basic CI workflow with basic general tests and screenshots
- [ ] Test on `chromium` and `firefox`

## User-facing changes

None, but hopefully we will be able to catch user facing issues such as things not rendering in the notebook.

Or trickier ones like #250 with Chromium.

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
@bollwyvl this PR is going with Galata for now, we should hopefully be able to reuse many of the helper functions that have been developed for stock JupyterLab (not tested yet, but should work in theory).

Maybe we can also have something Robot based on https://github.com/jupyterlite/jupyterlite/issues/6#issuecomment-875111498. Not sure if it will be redundant or complimentary. For now as long as we can have some sort of visual regression testing it should already be helpful.

**Comment by bollwyvl** [comment]
Welp, i'll be independently doing a set of human-readable `Lite` keywords  in `robotframework-jupyterlibrary` once we have something _i_ can stand behind (e.g. doesn't use CDN, etc).

fixtured-screenshot-comparison-based tests are my _least_ favorite kind of automated acceptance testing:

- maintaining the fixtures balloon the repo size
- contributor changes can have knock-on effects forcing someone to upgrade things unrelated to theirs
- unless taken very seriously, the results from CI are inscrutable
- merge conflicts are not possible

**Comment by jtpio** [comment]
> fixtured-screenshot-comparison-based tests are my _least_ favorite kind of automated acceptance testing:

Agree, these have already happened upstream in the JupyterLab repo and can be a bit annoying to deal with.

Another example of where these visual regression checks would however be useful: #265.

**Comment by bollwyvl** [comment]
> visual regression checks would however be useful

Oh, no need to argue with me into testing being important, but whenever we can use structured data vs basically raw binary comparison, we (and contributors) win. Maybe this is just a testing terminology, but "visual" suggests "pixels" to me, and they are frigging hard to corral between multiple browsers/operating systems versions.

Anyhow, if tasked with this, I'd add e.g. a fixture file:

```yaml
context_menu_items:
  notebook:
    - Download
    - Open with...
```

And a test:

```robotframework
*** Settings ***
Library    JupyterLibrary
Suite Setup     Run Keywords  Start JupyterLite Server    Open JupyterLite
Variables   filebrowser.yaml

*** Variables ***
${notebook file item}    css:.jp-DirListing-item[data-file-type="notebook"]
${context menu item}   xpath://span[contains(@class, 'lm-Menu-itemLabel')]

*** Test Cases ***
Notebook Context Menu in File Browser contains expected entries
    [tags]   gh:265
    Launch a new JupyterLab Document   Pyolite    Notebook
    Open Context Menu   ${notebook file item}
    FOR   ${label}  IN   ${context menu items.notebook}
       Page Should Contain Element    ${context menu item.notebook}\[contains(., "${label}")
    END
```

When this fails, it would say, in the CI logs:

```robotframework
Notebook Context Menu in File Browser contains expected entries     [FAIL]
  Element Did not appear in 5s   xpath://span[contains(@class, 'lm-Menu-itemLabel')][contains(., "Open With...")]
```

and create a `selenium-screenshot-1.png` vs

```
the same = false
```

If the team then decided that "context menus are important," and maybe icons, too, I'd hoist that to a reusable keyword, e.g. `Context Menu Should Contain   ${selector}  @{labels} @{icons}` so that we could, e.g. check _all_ of them (not fail on the first one). But really, i'd actually want to _test_ each of those.

Better still, if we had an oracle (e.g. full jupyterlab) to compare, and could _generate_ the expected data as a baseline, then only check in what we _don't_ have. Here, as well, one could capture specific areas of the DOM and use e.g. opencv to get a fuzzy comparison of two generated screenshots, from _the same browser_... but i usually only do this for highly critical/weird things like `canvas`-based renders where there is the expectation they will have pixel-level equivalence... and then also capture an actual visual diff as a third screenshot.

Of course, all of these mechanisms are hampered by a lack of GHA being able to publish ephemeral html assets for reports... i still haven't found a solution i really like for this. Futher, the concept of "coverage" becomes very challenging, but them's the breaks... best i've gotten to is, "new features that _can_ be tested get acceptance tests" and "all bugs get tagged acceptance tests".

**Comment by jtpio** [comment]
Closing in favor of #414

**Pull request closed without merging**
