### PR TITLE
fixed typo in logging call

### LINKED ISSUE #332: AttributeError: 'Logger' object has no attribute 'debu'
## Description

When running jupyterlite build locally using mulitple contents arguments, and files that are already resolved(?) causes an error.

`AttributeError: 'Logger' object has no attribute 'debu'`

Looks like a typo on:
https://github.com/jupyterlite/jupyterlite/blob/main/py/jupyterlite/src/jupyterlite/addons/contents.py#L117

## Reproduce

On the command line, call `jupyter lite build` with at least 4 contents arguments
My exact command to hit the error was:
```
jupyter lite build --contents 1402_Smoothing_surfaces --contents 1404_Euler_deconvolution --contents 1406_Make_a_synthetic/ --contents 1408_Evaluate_and_compare_colormaps/
```

obviously a typo in the code

- JupyterLite version: 0.1.0a6
- Operating System and version: Mac OS Big Sur
- Browser and version: n/a

<details><summary>CLI Output</summary>
<pre>
Traceback (most recent call last):
  File "/Users/stevejpurves/opt/anaconda3/lib/python3.8/site-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/stevejpurves/opt/anaconda3/lib/python3.8/site-packages/jupyterlite/addons/contents.py", line 24, in <lambda>
    pprint.pformat([str(p[0]) for p in self.file_src_dest]),
  File "/Users/stevejpurves/opt/anaconda3/lib/python3.8/site-packages/jupyterlite/addons/contents.py", line 24, in <listcomp>
    pprint.pformat([str(p[0]) for p in self.file_src_dest]),
  File "/Users/stevejpurves/opt/anaconda3/lib/python3.8/site-packages/jupyterlite/addons/contents.py", line 117, in file_src_dest
    self.log.debu("Already populated", resolved)
AttributeError: 'Logger' object has no attribute 'debu'
</pre>
</details>

### PR DESCRIPTION
**Pull request by stevejpurves**
## References

 fixes #332 

## Code changes

fixed a typo in the logging call

### CODE REVIEW

**Comment by stevejpurves** [comment]
By the way, I did a clean checkout of my fork here, and tried to run `doit` as per the contributing guide.

This caused `black` to reformat a bunch of files that I was not expecting (changes not committed here) and also `doit` hit an error.

image


Did I miss something?

**Comment by jtpio** [comment]
Thanks!

> This caused `black` to reformat a bunch of files that I was not expecting (changes not committed here) and also `doit` hit an error.

This looks odd indeed. The CI check for this PR looks good: https://github.com/jupyterlite/jupyterlite/pull/334/checks?check_run_id=3612750456

Also I quickly tried locally the latest `black` released yesterday and it seems to be working fine and doesn't change the files on disk: https://pypi.org/project/black/21.9b0/

**Comment by jtpio** [comment]
@stevejpurves mind opening a new issue to track that?

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by stevejpurves** [comment]
@jtpio I went back and double checked my environments, and that issue I posted above was my bad, and its resolved now. I am hitting other issues while onboarding though, and will open an issue around those.

**Comment by jtpio** [comment]
Thanks @stevejpurves.

Yes feel free to open a new issue. This will help troubleshoot and improve the contributing docs.

**Pull request merged**
