### PR TITLE
DOCS: unpin myst-nb

### PR DESCRIPTION
**Pull request by agoose77**
@jtpio this PR unpins myst-nb and hopefully fixes the warnings that were causing the docs build to fail!

### CODE REVIEW

**Comment by jtpio** [comment]
Nice, thanks @agoose77 for looking into this!

**Comment by jtpio** [comment]
This looks good to go. @agoose77 is there anything left to do on this PR, or is it ready to be undrafted and merged?

**Comment by agoose77** [comment]
@jtpio you have control!

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
