### PR TITLE
Update to lerna 6.4

### PR DESCRIPTION
**Pull request by jtpio**
## References

This might help fix a couple of dependabot alerts.

## Code changes

Update the `lerna` dependency.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by bollwyvl** [comment]
ideally, the `@jupyterlab/builder` most extension authors _must_ add to their package would _not_ rely on `verdaccio` at all.

if we actually use `verdaccio` in the release process for this, we can `resulitions: {"verdaccio": "file:packages/not-a-package"}` (with a dummy, but well-formed) `packages/not-a-package/package.json`, which will clobber a whole bunch of the alerts. `got` is still problematic.

**Comment by jtpio** [comment]
> ideally, the `@jupyterlab/builder` most extension authors _must_ add to their package would _not_ rely on `verdaccio` at all.

Right, we should probably open an issue upstream in JupyterLab and try to fix this.

**Comment by jtpio** [comment]
`verdaccio` is not used for the JupyterLite release process. But it is for JupyterLab.

**Comment by jtpio** [comment]
> Right, we should probably open an issue upstream in JupyterLab and try to fix this.

This is now tracked in https://github.com/jupyterlab/jupyterlab/issues/13740.

**Pull request merged**
