### PR TITLE
Add widgetsnbextension 4.x shim

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- starts #312
  - it's possible (but seems unlikely) every one or our upstream example dependencies is going to work out of the box with ipywidgets 8
  - this gives us a way to incrementally move forward.

## Code changes

- [x] rework dodo piplite indexing for multiple versions of the same package
- [x] add `widgetsnbextension4` shim package

## User-facing changes

- `await piplite.install('ipywidgets=8')` should work
  - note that `federated_extensions` only allow us to install one at a time
- downstream sites can start updating to `ipywidgets=8` without undue [hacks](https://github.com/deathbeds/ipydrawio/pull/99)

## Backwards-incompatible changes

- if not specified, it's possible mismatching versions of ipywidgets could get installed if not pre-cached
  - this might have been prevented previously by `widgetsnbextension` not being available

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

Looks good overall, but might need a second pass now that https://github.com/jupyterlite/jupyterlite/pull/791 has been merged:

https://github.com/jupyterlite/jupyterlite/blob/4da5f0157c2334fc3bf4979bfdb133ed09b6181a/dodo.py#L915

**Comment by bollwyvl** [comment]
tried to cheap merge, but will look more at "home" (another chair/laptop). 

I think for the RTD demo we need to hang tough with 7 until we're ready to look at #312 in earnest. I would think _missing_ demos is better than _broken_ demos, but we won't know until we look, and probably shouldn't wait, as it's causing active breakage.

**Comment by bollwyvl** [comment]
Tried everything out locally on RTD, etc. and widget-adjacent stuff looks ok with 7.

I'll start another PR that investigates going to 8.

**Review by martinRenou — APPROVED** [review]
Looks good to me!

I wonder why we needed a shim for widgetsnbextension in the first place? (I know I was the one adding it, but I don't recall why the piplite install was failing) Just asking because it'd be nice to get rid of this entirely at some point.

**Comment by bollwyvl** [comment]
I'll take another look at whether it is even needed...

**Comment by bollwyvl** [comment]
Opened #795 which doesn't ship the shim... the biggest downside is the wheel is 2mb of js we won't use inside the emscripten vm...

**Comment by martinRenou** [comment]
> the biggest downside is the wheel is 2mb of js we won't use inside the emscripten vm...

Yeah.. That's one good reason to keep the shim.

I remove the widgetsnbextension shim from emscripten-forge because it became a noarch package in conda-forge recently, but that makes me think we should probably filter out widgetsnbextension from what's included in the page.

**Comment by bollwyvl** [comment]
>  filter out widgetsnbextension

as mentioned in a few places: i am loathe to dig too much into the underlying `micropip` stuff to do that kind of surgery... there isn't a whole lot of stable API surface to work with.

**Comment by bollwyvl** [comment]
At any rate, #795 appears to be working well on the site. The only thing I could imagine that would improve things were if `ipywidgets` became a metapackage, somehow, and there was a way to install _just_ the kernel piece... the "simple" way, `ipywidgets[notebook,lab]` is unsatisfying for various reasons, though...

**Comment by bollwyvl** [comment]
Closing this in favor of the decision between #795 (simplicity) and #783 (speed)

**Pull request closed without merging**
