### PR TITLE
Update UI-tests snapshots

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by martinRenou** [comment]
update playwright snapshots

**Comment by jtpio** [comment]
Thanks!

Also spotted this in https://github.com/jupyterlite/jupyterlite/pull/1389, although not sure why they are failing because the snapshots were updated in https://github.com/jupyterlite/jupyterlite/pull/1376 with the CI passing.

**Comment by jtpio** [comment]
Ah maybe it's because of the pin on `jupyterlite-core`: https://github.com/jupyterlite/pyodide-kernel/blob/6d6c5ac485430f987006f32c2b8c4037d7ea5f6b/pyproject.toml#L40

**Comment by jtpio** [comment]
bot please update playwright snapshots

**Comment by martinRenou** [comment]
Diff looks ok, shall we merge? @jtpio

**Comment by jtpio** [comment]
Yes, the workflow to update the snapshots was not working properly (https://github.com/jupyterlite/jupyterlite/pull/1391).

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by martinRenou** [comment]
Thanks for fixing it!

**Pull request merged**
