### PR TITLE
Add the architecture diagram

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes https://github.com/jupyterlite/jupyterlite/issues/80

Using the diagram that has been used so far. So we have it somewhere now and can more easily be edited.

It is of course incomplete, but should still be accurate for now. Ideally we could produce something better later that would cover other aspects of JupyterLite (contents management, configuration) while making sure they don't get out of date too quickly.

## Code changes

Docs

## User-facing changes

In the developer docs:

image

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by bollwyvl** [comment]
Perhaps as follow-on, but... 
- put the image in `examples` so it's something people can play with... 
  - assuming `jupyter-drawio` can handle SVG... 
  - otherwise the XML there, and `.svg` in `docs`
    - and a check that the svg is always newer than the xml, gah
- can we put under any sort of test? 
  - from the codebase, we pull out number/names of:
    - apps
    - kernels
    - storage drivers
    - CDN providers
  - with e.g. `lxml` (or even standard lib) we pull out shapes/strings that should match the above
  - test fail if they do not agree
    - or even have them as notebooks that would show what's out-of-date (but not strictly _fail_)

i did a bit about this on [ipydrawio](https://ipydrawio--52.org.readthedocs.build/en/53/tutorials/designing-jupyter-extensions/index.html#testing)... that's specifically with the `.dio.svg` format, but would probably work with the straight-up `mxModel` dialect.

**Comment by jtpio** [comment]
> i did a bit about this on [ipydrawio](https://ipydrawio--52.org.readthedocs.build/en/53/tutorials/designing-jupyter-extensions/index.html#testing)

Maybe we can reuse some of this here too?

It would indeed be useful to have it in the examples and elaborate the pipeline. For now the idea was just to dump that diagram somewhere so it's more visible, but we can definitely improve that in follow-up PRs.

**Comment by bollwyvl** [comment]
Welp if you get the source xml into examples/, and a check that the svg is
up-to-date, we have enough to move forward with...

**Comment by bollwyvl** [comment]
The example is coming up empty on RTD...

**Comment by jtpio** [comment]
Ah that's weird.

I uploaded the svg on diagrams.net, and then download the `.drawio` from there.

**Comment by bollwyvl** [comment]
>  then download 

make sure the "compress and obfuscate xml" isn't on :rofl:

**Comment by bollwyvl** [comment]
Although, if you're dropping the already-generated SVG into a drawio doc, it will end up as a base64-encoded data URI, and its value for maintainability and testing is... diminished.

**Comment by jtpio** [comment]
The "source" is the SVG + metadata.

**Comment by jtpio** [comment]
Dropping https://github.com/jupyterlite/jupyterlite/pull/278/commits/a8728ed0167a1893a7e8510482c1e7b3ec7d8001 for now.

We can track it and the other items mentioned in https://github.com/jupyterlite/jupyterlite/pull/278#issuecomment-883448265 in separate issue(s).

**Comment by jtpio** [comment]
Merging so we don't block on this.

Happy to tackle the rest as part of #279, or @bollwyvl if you want to have a closer look feel free!

**Pull request merged**
