### PR TITLE
Update to JupyterLab 4.1 and Notebook 7.1

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes https://github.com/jupyterlite/jupyterlite/issues/1233
Fixes https://github.com/jupyterlite/jupyterlite/issues/1272
Fixes https://github.com/jupyterlite/jupyterlite/issues/1122

Start updating to the JupyterLab 4.1 and Notebook 7.1 pre-releases, to bring some of the new features.

And potentially catch some upstream issues as well.

## Code changes

- [x] Update `@jupyterlab` packages to `next`
- [x] Update `@jupyter-notebook` packages to `next`
- [x] Update `@lumino` packages to `latest`
- [x] Update to TypeScript 5.1
- [x] Include missing plugins / extensions
- [x] Update to Notebook `7.1.0a1` when available: https://github.com/jupyter/notebook/releases/tag/v7.1.0a1
- [x] Remove `jupyterlab-myst` from the demo site for now, to avoid issues with mermaid support
- [x] Fix UI tests. Some DOM elements have changed, as also noticed in https://github.com/jupyter/notebook/pull/7172

## User-facing changes

Some from JupyterLab 4.1 and Notebook 7.1.

**Mermaid diagrams**

image

## Backwards-incompatible changes

TBD

### CODE REVIEW

**Comment by bollwyvl** [comment]
Also, did we lose `@jupyterlab/celltags-extension` at some point (#25)?

**Comment by jtpio** [comment]
> Also, did we lose `@jupyterlab/celltags-extension` at some point (#25)?

Yes in JupyterLab 4.0: https://github.com/jupyterlab/jupyterlab/pull/14026

**Comment by jtpio** [comment]
> > Also, did we lose `@jupyterlab/celltags-extension` at some point (#25)?
> 
> Yes in JupyterLab 4.0: [jupyterlab/jupyterlab#14026](https://github.com/jupyterlab/jupyterlab/pull/14026)

Wait, wrong PR. Would need to double check.

**Comment by bollwyvl** [comment]
Had a look at RTD:
- myst clobbers the new built-in mermaid extension
  - its mermaid (which doesn't respect the well-known fenced style) cuts off text
- the cell tags are indeed absent
- leaflet is busted
  - `Module jupyter-leaflet, version ^0.18 is not registered, however,         0.17.4 is`
- some of the github sidebar icons don't show up

**Comment by bollwyvl** [comment]
here's a shot of local build of lab alpha (or maybe `main`) on the left and rtd on the right, both cranked up to 200% zoom (though is noticeable at lower levels of zoom:

image

**Comment by bollwyvl** [comment]
And the jl-gh:

image

**Comment by bollwyvl** [comment]
Re: pulling myst for the moment: I think it's appropriate on this PR, as it is relevant whether mermaid works for the release as we (well, probably I) could still do something about it upstream before the `4.1.0` release if there is a problem with it...

**Comment by jtpio** [comment]
This failure seems to be related to the upstream change in Galata (which now waits for a response from the contents API)
: https://github.com/jupyterlab/jupyterlab/pull/15021

image

**Comment by jtpio** [comment]
bot please update playwright snapshots

**Comment by jtpio** [comment]
Some upstream issues for which we might need a temporary workaround:

- https://github.com/jupyterlab/jupyterlab/issues/15629
- https://github.com/jupyter/notebook/issues/7210

**Comment by jtpio** [comment]
OK CI is now passing.

We might want to check how to fix upstream to avoid some Galata workarounds.

We can get this one in to be able to release a first `0.3.0` pre-release and continue iterating.

**Pull request merged**
