### PR TITLE
Add JupyterLab-github to the federated extensions

### PR DESCRIPTION
**Pull request by jasongrout**
## Code changes

The github extension pairs powerfully with jupyterlite to let people easily work on existing content on github, like tutorials, notebooks in package source repos, books on github, etc.

A motivation for this, for example, is the jupyter widgets tutorial at scipy, which may work really nicely with this github extension.

## User-facing changes

Adds a github file browser.

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

Indeed the extension is working really nicely on the ReadTheDocs preview:

image

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by bollwyvl** [comment]
By not adding this to `.binder/environment.yml`, this gets blown away when re-solving the demo with `doit env:lite:extensions`.... but it's not on conda-forge.

Have opened https://github.com/conda-forge/staged-recipes/pull/19761 so we can keep it up-to-date.

**Comment by jtpio** [comment]
> Have opened [conda-forge/staged-recipes#19761](https://github.com/conda-forge/staged-recipes/pull/19761) so we can keep it up-to-date.

Nice thanks for doing this!

**Pull request merged**
