### PR TITLE
Add `@jupyterlab/terminal-extension`

### PR DESCRIPTION
**Pull request by jtpio**
## References

Add `@jupyterlab/terminal-extension` to the build, to make it easier for extension to start experimenting with terminals in JupyterLite.

Some work-in-progress in https://github.com/ianthomas23/jupyterlite-terminal

Also related:

- https://github.com/jupyterlite/jupyterlite/issues/717
- https://github.com/jupyterlite/jupyterlite/issues/880
- https://github.com/jupyterlite/jupyterlite/issues/949

## Code changes

Add `@jupyterlab/terminal-extension` to the `lab` app.

## User-facing changes

Might enable terminals. To be documented later when there is an example that can be installed.

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
This seems to be helping with https://github.com/ianthomas23/jupyterlite-terminal/pull/2:

image

Let's get this in a pre-release so we can iterate more easily on the terminal extension.

**Comment by bollwyvl** [comment]
Sry, missed all the fun here.

It's important to make sure the full-fat xterm dependency _doesn't_ end up in the core bundle.

**Comment by jtpio** [comment]
> It's important to make sure the full-fat xterm dependency _doesn't_ end up in the core bundle.

It probably does. Although it looks like it's imported dynamically: https://github.com/jupyterlab/jupyterlab/blob/b2ff3fbbe60e1d08d23f6a4738d4f2d76f175152/packages/terminal/src/widget.ts#L604-L611

Otherwise an alternative could be to create a federated extension for `@jupyterlab/terminal-extension`.

**Comment by westurner** [comment]
Why not xterm.js? @bollwyvl 

Alternatives to xterm.js:

browsix: 
- src: https://github.com/plasma-umass/browsix
- https://browsix.org/ 

> Browsix does this by mapping low-level Unix primitives, like processes and system calls, onto existing browser APIs, like Web Workers and postMessage. [...]
>
> Processes are built on top of Web Workers, letting applications run in parallel and spawn subprocesses. System calls include fork, spawn, exec, and wait. [...]
>
> Shared Filesystem accessible from multiple processes.
>
> Thanks to a successful Summer of Code project, Browsix has an init system that supports managing and supervising in-browser services specified by systemd unit files.

- browsix has BrowserFS
- https://github.com/SamGinzburg/bash-browsix

BrowserFS:
- src: https://github.com/jvilk/BrowserFS
- > BrowserFS is an in-browser filesystem that emulates the Node JS filesystem API and supports storing and retrieving files from various backends. 

ZenFS:
- src: https://github.com/zen-fs
- docs: https://zenfs.dev/core/
- ZenFS is the successor to BrowserFS

hterm:
- src: https://github.com/libapps/libapps-mirror#top-level-directories :

> [ libdot: https://github.com/libapps/libapps-mirror/tree/main/libdot#libdot ]
>
> [hterm/](https://github.com/libapps/libapps-mirror/blob/main/hterm) is a JS library that provides a terminal emulator. It is reasonably fast, reasonably correct, and reasonably portable across browsers.
> 
> [nassh/](https://github.com/libapps/libapps-mirror/blob/main/nassh) is the Chrome Secure Shell extension that combines hterm with a build of OpenSSH to provide a PuTTY-like app for Chrome users.
> 
> [ssh_client/](https://github.com/libapps/libapps-mirror/blob/main/ssh_client) is the NaCl & WASM port of OpenSSH.


warp
- src: https://github.com/warpdotdev/Warp
- "Reducing WASM binary size: lessons from building a web terminal"
  https://www.warp.dev/blog/reducing-wasm-binary-size
  > 8MB
- "No Glyph Left Behind: Font Fallback in a WASM Terminal"
  https://www.warp.dev/blog/font-fallback-in-a-wasm-terminal
- https://www.npmjs.com/package/warp-wasm
  - This is someone else's build of warp in WASM fwics

bash:
- src: http://git.savannah.gnu.org/cgit/bash.git/
- src mirrror: https://github.com/bminor/bash
- https://www.google.com/search?q=how+to+build+bash+with+emsdk

zsh:
- src: git://git.code.sf.net/p/zsh/code
- src mirror: https://github.com/zsh-users/zsh

container2wasm:
- https://github.com/container2wasm/container2wasm
```sh
$ c2w ubuntu:22.04 out.wasm
```

**Comment by westurner** [comment]
container2wasm requires the xterm.js xterm-pty addon: https://github.com/mame/xterm-pty

ktock/vscode-container-wasm is a VScode extension for working with container2wasm containers: 
https://github.com/ktock/vscode-container-wasm#vscode-container-wasm-containers-on-vscode-for-the-web ::

> This extension runs containers on VSCode for the Web and provides Terminal to interact to it.
>
> The containers run in the WebAssembly VM on browser so you don't need prepare remote containers.
>
> HTTP(S) networking is also available in the container with restrictions by the browser (CORS-restricted and no control over Forbidden headers) (see also "Limitation" section).

Direct Sockets API: 
https://wicg.github.io/direct-sockets/
- https://chromestatus.com/feature/6398297361088512 ::
  - FF: No


gzuidhof/coi-serviceworker: https://github.com/gzuidhof/coi-serviceworker :

> Cross-origin isolation (COOP and COEP) through a service worker for situations in which you can't control the headers (e.g. GH pages)

**Pull request merged**
