### PR TITLE
Remove code references to pyolite, add BaseAddon methods

### LINKED ISSUE #995: Remove more of the `pyolite` hangover
### Problem

After #854, there are still some dangling references to `pyolite` that will cause confusion on the docs, etc.

### Proposed Solution

Remove the dangling references:

- constants ([renamed downstream](https://github.com/jupyterlite/pyodide-kernel/pull/19/files#diff-e90896b3695e1a7c57b585dc7c63ca9f80329d4ea5dc1935523c63fa30c8928aR14))
- schema entries (https://github.com/jupyterlite/pyodide-kernel/pull/19/commits/015e1a390e88a6012b66ee2a9a53989be285ee57)
- kernelspec/icon (https://github.com/jupyterlite/pyodide-kernel/pull/19#issuecomment-1462252729)

Update docs:

- use the new in-place schema from `jupyterlite-pyodide-kernel`
  - describe migration approaches

### Additional context

- probably blocked by 
  - #994 
  - https://github.com/jupyterlite/pyodide-kernel/pull/19

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- probably keep in draft until #994
- blocked by https://github.com/jupyterlite/pyodide-kernel/pull/19
- fixes #995
- first part of #996
  - pulls the new settings/paths methods from https://github.com/jupyterlite/pyodide-kernel/pull/19

## Code changes

- [x] `app`
  - [x] remove the `pyolite` stanza from schema
  - [x] remove the `piplite` schema
  - [x] remove the python kernel icon
- [x] `BaseAddon`
  - [x] adds `lite` and `output` config path finders
  - [x] adds getter/setter for lite plugins by id
- [x] `dodo.py`
  - [x] remove piplite references, task

## User-facing changes

- n/a (`pyodide-kernel` uses upstream branding)

## Backwards-incompatible changes

- actually, kinda as these were previously part of the API

### CODE REVIEW

**Comment by bollwyvl** [comment]
Yep, kernel icon definitely broken! No need to look at the UI report.

image


Just means screenshot-based tests in the docs site would be coupled with tightly pinned downstream versions...  certainly possible that e.g. the pyodide logo might change, if only to add a dark-mode-friendly version.

**Comment by jtpio** [comment]
> Just means screenshot-based tests in the docs site would be coupled with tightly pinned downstream versions... certainly possible that e.g. the pyodide logo might change, if only to add a dark-mode-friendly version.

Right. Same goes with the p5 kernel. I think the screenshot helped catch a regression in the past with federated kernels not loaded.

I would say it's fine if the Pyodide kernel changes later and we need to update here. Normally it shouldn't change that often after reaching a good version.

**Comment by jtpio** [comment]
Opened https://github.com/jupyterlite/jupyterlite/pull/1000 for now to help with this.

**Comment by bollwyvl** [comment]
>  drop the Pyodide kernel from the UI tests

Even in another repo, and even leaving space for other repos, I think "breaks the latest (or a pre-)release of `pyodide-kernel`" is still pretty much "can't go to space today."

**Comment by bollwyvl** [comment]
> JupyterLab that depends on

Dude, on LSP we try to keep _x_ kernels + _y_ language servers working under automated. It's awful. But that's how it goes to build tools not wrapped around "the one true" implementation.

**Comment by bollwyvl** [comment]
This doesn't update any docs, but is probably still ready for looking at.

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
Will publish a `jupyterlite-core==0.1.0a1` for testing so it can be used in https://github.com/jupyterlite/pyodide-kernel.

**Pull request merged**
