### PR TITLE
Support more sources of federated_extension

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- tangentially addresses #151
  - though that's more about the py-in-js packages for `pyolite`
    - but the `.whl` downloading (which definitely _should_ be shared between them) is reusable (and really dumb)

## Code changes

- [x] add a `--cache-dir` (default: `{lite_dir}/.cache`)
  - for downloading archives
  - ideally would be shareable between multiple builds
- [x] adds to `LiteBuildConfig`
  - [x] `--ignore-sys-prefix` to disable the env scraping stuff 
  - [x] `--federated-extensions`, which accepts
    - [x] local and remote `.whl` files
    - [x] local folders that contain a `package.json` 
    - [x] conda `.tar.bz2`
      - [x] local
      - [x] remote 
      - [x] ~~`anaconda.org`~~ doesn't work because of redirects, not going to add special case
    - [ ] other well-known archive formats/layouts? 
      - I don't want to go mucking around too much...
- [x] use `--federated-extensions` in docs build  for ~~_all_~~ of the extensions
  - [x] will make RTD ~~_much_~~ somewhat faster
  - [x] keep the goods in binder
  - [x] cache the downloaded conda packages, rather than trying to find them
- [x] update docs
- [x] add tests (currently fails coverage threshold :crying_cat_face:)
  - [x] checked-in smallest extension (which has a theme, mime, settings, etc)
  - [ ] ideally we'd already be _building_ a labextension to test with, (#165), but will probably just download a fixture, pull it out of the local wheel cache, etc.

## User-facing changes

- CLI users will have more options, especially in CI, for builds

## Backwards-incompatible changes

- renamed a few members on the addons... no too worried about breakage at that layer at this time

### CODE REVIEW

**Comment by bollwyvl** [comment]
Of note, a conda-forge URL can be be predictably transformed from:

```http
https://conda.anaconda.org/conda-forge/noarch/jupyterlab-gt-coar-theme-0.3.0-pyhd8ed1ab_0.tar.bz2
```

to:

```http
https://github.com/conda-forge/releases/releases/download/noarch/jupyterlab-gt-coar-theme-0.3.0-pyhd8ed1ab_0.tar.bz2/jupyterlab-gt-coar-theme-0.3.0-pyhd8ed1ab_0.tar.bz2
```

> yerp, `releases/releases` and `.bz2/....bz2` :shrug: 

This URL is _probably_ throttled, though... but _maybe_ we could offer it as a translation.

**Comment by bollwyvl** [comment]
My previous [build](https://readthedocs.org/projects/jupyterlite/builds/14200068/) for 24763bc took:
- 792 seconds

Imma guess... ~740 :crossed_fingers: :popcorn:

**Comment by bollwyvl** [comment]
Welp, it failed... but it failed _faster_! ` 636`

Was:

```
[rtd-command-info] start-time: 2021-07-09T14:13:01.498605Z, end-time: 2021-07-09T14:13:54.219586Z, duration: 52, exit-code: 0
```

Now:

```
[rtd-command-info] start-time: 2021-07-09T03:54:47.647757Z, end-time: 2021-07-09T03:56:02.804552Z, duration: 75, exit-code: 0
mamba env create --quiet --name 238 --file docs/environment.yml
```

So _maybe_ not worth the complexity. It kinda blows me away that they implemented the mamba thing as _use conda to install mamba_ when they could roll a container:

```
[rtd-command-info] start-time: 2021-07-09T03:51:57.916166Z, end-time: 2021-07-09T03:54:47.494956Z, duration: 169, exit-code: 0
conda install --yes --quiet --name=base --channel=conda-forge python=3.7 mamba
```

**Comment by bollwyvl** [comment]
Gah, apparently the docs notebooks `import pandas` (which is no longer installed)

**Comment by bollwyvl** [comment]
So, actually _passing_ it takes 767s.

Thirty seconds isn't nothing, of course... and every time we add another extension, there's the risk of it driving it up further.

Very possibly we could run more `doit` jobs at once (except for `build:prod`) and knock some more time off.

Also the reproducibility check (and the archive creation in the first place) is pretty much vanity (and help catch errors in a visual way) but these are checked in the per-platform tests, anyway. We can probably take them out (or gate them behind an env var check, so we're at least running them locally. Similarly, the demo app archive that gets built isn't _linked to_ from anywhere in the docs... so maybe we drop that, too, and just keep it in the release workflow.

Of course, making these _faster_ with an optional `libarchive-c` dependency might be better... while folk won't be _building_ archives all the time, they will be unpacking that 20mb every time.

**Comment by bollwyvl** [comment]
RTD builds now seem to hover right around 720-740 ms, which seems like it's probably worth the changes.

I've got `the-smallest-extension` locally, and could add it to `packages` (or a new top-level/nested folder) and squash out the checked-in `.whl` and conda `.tar.bz2`... even with `micromamba` or whtatever, adding `conda-build` ratchets up the complexity/time/flakiness pretty substantially, but could be a parallel concern that _only_ worries about that... and would cache quite well.

Otherwise, this is probably good to go.

**Comment by jtpio** [comment]
Thanks!

Looks like there is a minor conflict to fix, but otherwise looks good :+1:

**Comment by jtpio** [comment]
Arf, one more conflict so we can add `ipycytoscape` (from #256) to the demo site.

**Comment by bollwyvl** [comment]
will try resolving with the web ui...

**Comment by bollwyvl** [comment]
Yeah, `ipyctoscape` and its deps are not exactly lightweight... `Build took 813 seconds`...

**Comment by jtpio** [comment]
> Yeah, `ipyctoscape` and its deps are not exactly lightweight... `Build took 813 seconds`...

Maybe we could start offloading some of these dependencies and examples to https://github.com/jupyterlite/demo?

And keep https://jupyterlite.github.io/demo/ as the "stable" demo, and https://jupyterlite.rtfd.io/en/latest/try/lab  be the "nightly". This could help keep snappier previews here for development.

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
