### PR TITLE
Clean up various log warnings

### LINKED ISSUE #466: Disable fetching `jupyter-lite.ipynb`
### Problem

Site deployers sometimes want a clean dev tools console with no error.

At the moment JupyterLite tries to fetch configuration files from well-known places, such as `jupyter-lite.ipynb`. This often leads to 404s, for example:

image

### Proposed Solution

Either a default `jupyter-lite.ipynb` is created on build, or fetching `jupyter-lite.ipynb` is made configurable.

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- [x] fixes #466

## Code changes

- [x] fix some eslint warnings
- [x] hide some pytest warnings
  - [x] created upstream PR: https://github.com/jupyter-server/jupyter_server_mathjax/pull/11  
    - [x] release as `0.2.4`
- [x] add empty `jupyter-lite.ipynb` at various levels to make browser logs quieter
  - do we want to drop leaflet? https://github.com/jupyter-widgets/ipyleaflet/issues/473
- [x] remove `console.log`s
  - [x] various app `index.ts`
  - [x] pyodide `execute-request` console.log`
    - [x] _the initial `pyodide.loadPackage` could accept callbacks for info and error... we should probably route those to the in-UI log console, but that's probably out of scope here._
- [x] un (and maybe re-pin) all of the pyodide labextension/kernel packages for updates

## User-facing changes

- end users should see fewer spurious browser log warnings
  - > Screenshot from 2022-02-05 16-23-58
 
- site builders should see fewer spurious build log errors
- contributors should see fewer spurious log errors

## Backwards-incompatible changes

- n/a

### CODE REVIEW

**Comment by bollwyvl** [comment]
Looks like GHA, etc. is having A Day... will take a further look tomorrow...

**Comment by jtpio** [comment]
Thanks!

Looks like CI is now green :heavy_check_mark:

**Comment by bollwyvl** [comment]
This is ready for review: I have some follow-on work I want to do, and will make additional issues.

**Review by jtpio — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
